name: Docker Image CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/c-noblet/papagei-api:latest

    - name: Run Container
      run: docker run -d -p 8080:8080 --name papagei-api ghcr.io/c-noblet/papagei-api:latest

    - name: Run tests
      run: docker exec papagei-api yarn run test

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: c-noblet
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Push Docker image in repository
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./
        # Note: tags has to be all lower-case
        tags: ghcr.io/c-noblet/papagei-api:latest
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}
      run: docker push ghcr.io/c-noblet/papagei-api:latest
