name: Docker Image CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag papagei-api:$(date +%s)

    - name: Run Container
      run: docker run -d -p 8080:8080 -v $PWD/dist:/home/node/papagei-api/dist --name papagei-api papagei-api

    - name: Run tests
      run: docker exec -it papagei-api yarn run test
